syntax = "proto3";

option java_package = "protonova.protobuf";
option java_outer_classname = "DamageProto";

message DamageMultiplier {
    optional double brute = 1;
    optional double asphyxiation = 2;
    optional double burn = 3;
    optional double toxin = 4;
    optional double genetic = 5;
    optional double structural = 6;
    optional double bleeding = 7;
}

message Damage {
	int32 bruteDamage = 2;
	int32 asphyxiationDamage = 3;
	int32 burnDamage = 4;
	int32 toxinDamage = 5;
	int32 geneticDamage = 6;
	int32 structuralDamage = 7;
	double bleedingPerTick = 8;
	DamageMultiplier damageMultiplier = 9;
}

message HitDamage {
	optional int32 bruteDamage = 2;
	optional int32 asphyxiationDamage = 3;
	optional int32 burnDamage = 4;
	optional int32 toxinDamage = 5;
	optional int32 geneticDamage = 6;
	optional int32 structuralDamage = 7;
	optional double bleedingPerTick = 8;
}