syntax = "proto3";

option java_package = "protonova.protobuf";
option java_outer_classname = "EntityProto";

import "vector.proto";

enum Direction {
	Up = 0;
	Down = 1;
	Left = 2;
	Right = 3;
}


message Entity {
  string name = 1;
  Vector position = 2;
  int32 map = 3;
  int32 id = 4;
  double speed = 5;
  Vector velocity = 6;
  bool isItem = 7;
  map<string,int32> inventorySlots = 8;
  bool anchored = 9;
  bool canCollide = 10;
  Direction direction = 11;
  int32 health = 12;
  int32 maxHealth = 13;
  Vector size = 14;
  string selectedSlot = 15;
  optional bool stackable = 16;
  optional int32 amount = 17;
}
