syntax = "proto3";

option java_package = "protonova.protobuf";
option java_outer_classname = "EntityProto";

import "vector.proto";
import "damage.proto";
import "organs.proto";
import "chemical.proto";
import "lootTableItem.proto";

enum Direction {
	Up = 0;
	Down = 1;
	Left = 2;
	Right = 3;
}


message Entity {
  string name = 1;
  Vector position = 2;
  int32 map = 3;
  int32 id = 4;
  double speed = 5;
  Vector velocity = 6;
  bool isItem = 7;
  map<string,int32> inventorySlots = 8;
  bool anchored = 9;
  bool canCollide = 10;
  Direction direction = 11;
  int32 critHealth = 12;
  int32 maxHealth = 13;
  Vector size = 14;
  string selectedSlot = 15;
  optional bool stackable = 16;
  optional int32 amount = 17;
  optional float lightRange = 18;
  optional string hexColor = 19;
  bool castShadow = 21;
  optional string displayTexture = 22;
  repeated string tags = 23;
  Damage damage = 24;
  Organs organs = 25;
  double reach = 26;
  HitDamage hitDamage = 27;
  bool alive = 28;
  double maxSpeed = 29;
  bool dropsABody = 30;
  repeated lootTableItem lootTable = 31;
  map<string,int32> internal = 32;
  int32 internalSpace = 33;
  // Items can only receive attacks when this is enabled. Non-items ignore it.
  bool canDestroy = 34;
  OrganSlots organSlots = 35;
  OrganAssetSlots organAssetSlots = 36;
  OrganComponent organComponent = 37;
  // Higher values are rendered and selected above entities with lower values.
  sint32 renderPriority = 38;
  int32 temperature = 39;
  repeated Chemical chemicals = 40;
  bool consumable = 41;
}
